# hologram config
# スタイルガイドのもとになるスタイルシートファイルがあるディレクトリ
source: ../app/stylesheets
# スタイルガイドの書き出し先のディレクトリ
destination: ../styleguide
# スタイルガイドのテンプレートがあるディレクトリ
documentation_assets: templates
# Markdown をパースするときに実行する Ruby ファイル
custom_markdown: markdown_renderer.rb
# スタイルガイドの名前
styleguide_name: 'Sample Style Guide'
